local addonName, addonTable = ...

local L = LibStub("AceLocale-3.0"):GetLocale("Rarity")
local CONSTANTS = addonTable.constants

if LE_EXPANSION_LEVEL_CURRENT < LE_EXPANSION_DRAGONFLIGHT then
	return {}
end

local dragonflightManuscripts = {
-- 10.0 Dragon Racer's Purse
	-- Renewed Proto Drake
	["Renewed Proto-Drake: Dual Horned Crest"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Renewed Proto-Drake: Dual Horned Crest"],
		itemId = 197366,
		items = { 199192 },
		chance = 50,
		questId = { 69567 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
			{ m = CONSTANTS.UIMAPIDS.THALDRASZUS },
		},
	},
	["Renewed Proto-Drake: Thin Spined Jaw"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Renewed Proto-Drake: Thin Spined Jaw"],
		itemId = 197387,
		items = { 199192 },
		chance = 50,
		questId = { 69588 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
			{ m = CONSTANTS.UIMAPIDS.THALDRASZUS },
		},
	},
	-- Windborne Velocidrake
	["Windborne Velocidrake: Hooked Snout"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Windborne Velocidrake: Hooked Snout"],
		itemId = 197619,
		items = { 199192 },
		chance = 50,
		questId = { 69823 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
			{ m = CONSTANTS.UIMAPIDS.THALDRASZUS },
		},
	},
	["Windborne Velocidrake: Curled Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Windborne Velocidrake: Curled Horns"],
		itemId = 197605,
		items = { 199192 },
		chance = 50,
		questId = { 69809 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
			{ m = CONSTANTS.UIMAPIDS.THALDRASZUS },
		},
	},
	-- Highland Drake
	["Highland Drake: Curled Back Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Highland Drake: Curled Back Horns"],
		itemId = 197128,
		items = { 199192 },
		chance = 50,
		questId = { 69329 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
			{ m = CONSTANTS.UIMAPIDS.THALDRASZUS },
		},
	},
	["Highland Drake: Swept Spiked Head"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Highland Drake: Swept Spiked Head"],
		itemId = 197113,
		items = { 199192 },
		chance = 50,
		questId = { 69314 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
			{ m = CONSTANTS.UIMAPIDS.THALDRASZUS },
		},
	},
	["Highland Drake: Hooked Tail"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Highland Drake: Hooked Tail"],
		itemId = 197152,
		items = { 199192 },
		chance = 50,
		questId = { 69353 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
			{ m = CONSTANTS.UIMAPIDS.THALDRASZUS },
		},
	},
	-- Cliffside Wylderdrake
	["Cliffside Wylderdrake: Large Tail Spikes"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Cliffside Wylderdrake: Large Tail Spikes"],
		itemId = 197017,
		items = { 199192 },
		chance = 50,
		questId = { 69169 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
			{ m = CONSTANTS.UIMAPIDS.THALDRASZUS },
		},
	},
	["Cliffside Wylderdrake: Spiked Brow"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Cliffside Wylderdrake: Spiked Brow"],
		itemId = 196971,
		items = { 199192 },
		chance = 50,
		questId = { 69171 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
			{ m = CONSTANTS.UIMAPIDS.THALDRASZUS },
		},
	},
	["Cliffside Wylderdrake: Curled Head Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Cliffside Wylderdrake: Curled Head Horns"],
		itemId = 196979,
		items = { 199192 },
		chance = 50,
		questId = { 69179 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
			{ m = CONSTANTS.UIMAPIDS.THALDRASZUS },
		},
	},
-- 10.0.7 Reach Racer's Purse
	-- Renewed Proto Drake
	["Renewed Proto-Drake: Plated Brow"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Renewed Proto-Drake: Plated Brow"],
		itemId = 202274,
		items = { 204359 },
		chance = 50,
		questId = { 73055 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_FORBIDDEN_REACH },
		},
	},
	-- Windborne Velocidrake
	["Windborne Velocidrake: Small Ears"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Windborne Velocidrake: Small Ears"],
		itemId = 197594,
		items = { 204359 },
		chance = 50,
		questId = { 69798 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_FORBIDDEN_REACH },
		},
	},
	-- Highland Drake
	["Highland Drake: Swept Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Highland Drake: Swept Horns"],
		itemId = 197124,
		items = { 204359 },
		chance = 50,
		questId = { 69325 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_FORBIDDEN_REACH },
		},
	},
	-- Cliffside Wylderdrake
	["Cliffside Wylderdrake: Flared Cheek"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Cliffside Wylderdrake: Flared Cheek"],
		itemId = 197002,
		items = { 204359 },
		chance = 50,
		questId = { 69202 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_FORBIDDEN_REACH },
		},
	},
-- 10.1 Cavern Racer's Purse
	-- Renewed Proto Drake
	["Renewed Proto-Drake: Pronged Tail"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Renewed Proto-Drake: Pronged Tail"],
		itemId = 202280,
		items = { 205226 },
		chance = 50,
		questId = { 73060 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.ZARALEK_CAVERN },
		},
	},
	-- Highland Drake
	["Highland Drake: Tapered Chin"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Highland Drake: Tapered Chin"],
		itemId = 197104,
		items = { 205226 },
		chance = 50,
		questId = { 69305 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.ZARALEK_CAVERN },
		},
	},
	-- Cliffside Wylderdrake
	["Cliffside Wylderdrake: Split Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Cliffside Wylderdrake: Split Horns"],
		itemId = 196997,
		items = { 205226 },
		chance = 50,
		questId = { 69197 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.ZARALEK_CAVERN },
		},
	},
	["Cliffside Wylderdrake: Small Head Spikes"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Cliffside Wylderdrake: Small Head Spikes"],
		itemId = 196978,
		items = { 205226 },
		chance = 50,
		questId = { 69178 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.ZARALEK_CAVERN },
		},
	},
	-- Winding Slitherdrake
	["Winding Slitherdrake: Triple Jaw Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Winding Slitherdrake: Triple Jaw Horns"],
		itemId = 203342,
		items = { 205226 },
		chance = 50,
		questId = { 73833 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.ZARALEK_CAVERN },
		},
	},
	["Winding Slitherdrake: Small Finned Crest"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Winding Slitherdrake: Small Finned Crest"],
		itemId = 203317,
		items = { 205226 },
		chance = 50,
		questId = { 73805 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.ZARALEK_CAVERN },
		},
	},
	["Winding Slitherdrake: Pointed Nose"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Winding Slitherdrake: Pointed Nose"],
		itemId = 203348,
		items = { 205226 },
		chance = 50,
		questId = { 73839 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.ZARALEK_CAVERN },
		},
	},
	["Winding Slitherdrake: Finned Tip Tail"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Winding Slitherdrake: Finned Tip Tail"],
		itemId = 203361,
		items = { 205226 },
		chance = 50,
		questId = { 73853 },
		coords = { { m = CONSTANTS.UIMAPIDS.ZARALEK_CAVERN } },
	},
-- 10.2 Dream Racer's Purse
	-- Winding Slitherdrake
	["Winding Slitherdrake: Large Finned Tail"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Winding Slitherdrake: Large Finned Tail"],
		itemId = 203360,
		items = { 210549 },
		chance = 50,
		questId = { 73852 },
		coords = { { m = CONSTANTS.UIMAPIDS.THE_EMERALD_DREAM } },
	},
	["Winding Slitherdrake: Hairy Jaw"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Winding Slitherdrake: Hairy Jaw"],
		itemId = 203343,
		items = { 210549 },
		chance = 50,
		questId = { 73834 },
		coords = { { m = CONSTANTS.UIMAPIDS.THE_EMERALD_DREAM } },
	},
	["Winding Slitherdrake: Thorn Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Winding Slitherdrake: Thorn Horns"],
		itemId = 203337,
		items = { 210549 },
		chance = 50,
		questId = { 73827 },
		coords = { { m = CONSTANTS.UIMAPIDS.THE_EMERALD_DREAM } },
	},
	["Winding Slitherdrake: Short Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Winding Slitherdrake: Short Horns"],
		itemId = 203333,
		items = { 210549 },
		chance = 50,
		questId = { 73822 },
		coords = { { m = CONSTANTS.UIMAPIDS.THE_EMERALD_DREAM } },
	},
	-- Grotto Netherwing Drake
	["Grotto Netherwing Drake: Cluster Spiked Crest"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Grotto Netherwing Drake: Cluster Spiked Crest"],
		itemId = 207765,
		items = { 210549 },
		chance = 50,
		questId = { 77136 },
		coords = { { m = CONSTANTS.UIMAPIDS.THE_EMERALD_DREAM } },
	},
	["Grotto Netherwing Drake: Double Finned Tail"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Grotto Netherwing Drake: Double Finned Tail"],
		itemId = 207778,
		items = { 210549 },
		chance = 50,
		questId = { 77149 },
		coords = { { m = CONSTANTS.UIMAPIDS.THE_EMERALD_DREAM } },
	},
	["Grotto Netherwing Drake: Volatile Pattern"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Grotto Netherwing Drake: Volatile Pattern"],
		itemId = 207768,
		items = { 210549 },
		chance = 50,
		questId = { 77139 },
		coords = { { m = CONSTANTS.UIMAPIDS.THE_EMERALD_DREAM } },
	},
	["Grotto Netherwing Drake: Spiked Back"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Grotto Netherwing Drake: Spiked Back"],
		itemId = 207758,
		items = { 210549 },
		chance = 50,
		questId = { 77129 },
		coords = { { m = CONSTANTS.UIMAPIDS.THE_EMERALD_DREAM } },
	},

-- 10.0 Manuscripts from Rares / World Bosses / Treasures
	-- Renewed Proto Drake
	["Renewed Proto-Drake: Impaler Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Renewed Proto-Drake: Impaler Horns"],
		itemId = 197379,
		npcs = { 195915, 192737, 193668 },
		chance = 50,
		questId = { 69580 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.THALDRASZUS },
		},
	},
	["Renewed Proto-Drake: Gray Hair"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Renewed Proto-Drake: Gray Hair"],
		itemId = 197367,
		npcs = { 193227, 189652, 192045, 192020 },
		chance = 50,
		questId = { 69568 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
		},
	},
	["Renewed Proto-Drake: Heavy Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Renewed Proto-Drake: Heavy Horns"],
		itemId = 197383,
		npcs = { 187209, 190991, 193669, 193215 },
		chance = 50,
		questId = { 69584 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
		},
	},
	["Renewed Proto-Drake: Club Tail"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Renewed Proto-Drake: Club Tail"],
		itemId = 197403,
		npcs = { 187111, 193722, 193256, 196010, 193143, 193243 },
		chance = 50,
		questId = { 69604 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THALDRASZUS },
		},
	},
	["Renewed Proto-Drake: White Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Renewed Proto-Drake: White Horns"],
		itemId = 197382,
		npcs = { 193256, 193154, 187559, 193178, 193691 },
		chance = 50,
		questId = { 69583 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
		},
	},
	["Renewed Proto-Drake: Finned Tail"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Renewed Proto-Drake: Finned Tail"],
		itemId = 197404,
		npcs = { 193178 },
		chance = 50,
		questId = { 69605 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
		},
	},
	["Renewed Proto-Drake: Snub Snout"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Renewed Proto-Drake: Snub Snout"],
		itemId = 197398,
		npcs = { 197354 },
		chance = 50,
		questId = { 69599 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
		},
	},
	["Renewed Proto-Drake: Shark Snout"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Renewed Proto-Drake: Shark Snout"],
		itemId = 197400,
		npcs = { 197009, 193196 },
		chance = 50,
		questId = { 69601 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
		},
	},
	["Renewed Proto-Drake: Purple Hair"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Renewed Proto-Drake: Purple Hair"],
		itemId = 197372,
		npcs = { 193209, 193669, 191354, 193176 },
		chance = 50,
		questId = { 69573 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THALDRASZUS },
		},
	},
	-- Windborne Velocidrake
	["Windborne Velocidrake: Cluster Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Windborne Velocidrake: Cluster Horns"],
		itemId = 197602,
		npcs = { 187209, 190991, 193669 },
		chance = 50,
		questId = { 69806 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
		},
	},
	["Windborne Velocidrake: Large Head Fin"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Windborne Velocidrake: Large Head Fin"],
		itemId = 197589,
		npcs = { 193118, 193226, 193181, 194392 },
		chance = 50,
		questId = { 69793 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
		},
	},
	["Windborne Velocidrake: Club Tail"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Windborne Velocidrake: Club Tail"],
		itemId = 197624,
		npcs = { 187209, 187886, 189289, 190991},
		chance = 50,
		questId = { 69828 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
		},
	},
	["Windborne Velocidrake: Swept Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Windborne Velocidrake: Swept Horns"],
		itemId = 197606,
		npcs = { 193209, 193669, 193176 },
		chance = 50,
		questId = { 69810 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THALDRASZUS },
		},
	},
	["Windborne Velocidrake: Gray Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Windborne Velocidrake: Gray Horns"],
		itemId = 197608,
		npcs = { 193118, 186827, 193235, 184456, 190244 },
		chance = 50,
		questId = { 69813 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
		},
	},
	["Windborne Velocidrake: Spiked Back"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Windborne Velocidrake: Spiked Back"],
		itemId = 197586,
		npcs = { 187745, 193214, 193664 },
		chance = 50,
		questId = { 69790 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
			{ m = CONSTANTS.UIMAPIDS.THALDRASZUS },
		},
	},
	["Windborne Velocidrake: Finned Ears"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Windborne Velocidrake: Finned Ears"],
		itemId = 197595,
		npcs = { 193259 },
		chance = 5,
		questId = { 69799 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
		},
	},
	["Windborne Velocidrake: Feathery Head"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Windborne Velocidrake: Feathery Head"],
		itemId = 197593,
		npcs = { 193258 },
		chance = 50,
		questId = { 69797 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THALDRASZUS },
		},
	},
	["Windborne Velocidrake: White Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Windborne Velocidrake: White Horns"],
		itemId = 197609,
		npcs = { 201013 },
		chance = 50,
		questId = { 69813 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.FORBIDDEN_REACH },
		},
	},
	["Windborne Velocidrake: Shrieker Pattern"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Windborne Velocidrake: Shrieker Pattern"],
		itemId = 197636,
		npcs = { 200956 },
		chance = 50,
		questId = { 69847 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.FORBIDDEN_REACH },
		},
	},
	["Windborne Velocidrake: Small Head Fin"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Windborne Velocidrake: Small Head Fin"],
		itemId = 197590,
		npcs = { 200978 },
		chance = 50,
		questId = { 69794 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.FORBIDDEN_REACH },
		},
	},
	["Windborne Velocidrake: Plated Neck"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Windborne Velocidrake: Plated Neck"],
		itemId = 197628,
		npcs = { 200885 },
		chance = 50,
		questId = { 69834 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.FORBIDDEN_REACH },
		},
	},
	["Windborne Velocidrake: Heavy Scales"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Windborne Velocidrake: ITEMNAME"],
		itemId = 197617,
		npcs = { 200911 },
		chance = 50,
		questId = { 69821 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.FORBIDDEN_REACH },
		},
	},
	-- Highland Drake
	["Highland Drake: Finned Back"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Highland Drake: Finned Back"],
		itemId = 197098,
		npcs = { 196056, 187945 },
		chance = 50,
		questId = { 69299 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
		},
	},
	["Highland Drake: Maned Head"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Highland Drake: Maned Head"],
		itemId = 197111,
		npcs = { 184853, 192949, 194401, 193273 },
		chance = 50,
		questId = { 69312 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
			{ m = CONSTANTS.UIMAPIDS.THALDRASZUS },
		},
	},
	["Highland Drake: Toothy Mouth"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Highland Drake: Toothy Mouth"],
		itemId = 197135,
		npcs = { 195915, 192737 },
		chance = 50,
		questId = { 69336 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
		},
	},
	["Highland Drake: Striped Pattern"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Highland Drake: Striped Pattern"],
		itemId = 197138,
		npcs = { 187745, 193214, 193664 },
		chance = 50,
		questId = { 69339 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
			{ m = CONSTANTS.UIMAPIDS.THALDRASZUS },
		},
	},
	["Highland Drake: Club Tail"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Highland Drake: Club Tail"],
		itemId = 197149,
		npcs = { 193235, 184456, 190244 },
		chance = 50,
		questId = { 69350 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
		},
	},
	["Highland Drake: Spiked Club Tail"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Highland Drake: Spiked Club Tail"],
		itemId = 197150,
		npcs = { 192749, 198004 },
		chance = 20,
		questId = { 69351 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
		},
	},
	["Highland Drake: Finned Head"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Highland Drake: Finned Head"],
		itemId = 197106,
		npcs = { 197009, 193196 },
		chance = 50,
		questId = { 69307 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
		},
	},
	["Highland Drake: Spined Chin"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Highland Drake: Spined Chin"],
		itemId = 197105,
		npcs = { 193885, 193188, 196165 },
		chance = 50,
		questId = { 69306 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
		},
	},
	["Highland Drake: Crested Brow"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Highland Drake: Crested Brow"],
		itemId = 197100,
		npcs = { 187745, 194402, 195300, 193664 },
		chance = 50,
		questId = { 69301 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
			{ m = CONSTANTS.UIMAPIDS.THALDRASZUS },
		},
	},
	["Highland Drake: Ears"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Highland Drake: Ears"],
		itemId = 197116,
		npcs = { 197116 },
		chance = 50,
		questId = { 193271, 69317 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.ZARALEK_CAVERN },
		},
	},
	["Highland Drake: Tan Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Highland Drake: Tan Horns"],
		itemId = 197121,
		npcs = { 197354 },
		chance = 50,
		questId = { 69322 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
		},
	},
	["Highland Drake: Thorned Jaw"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Highland Drake: Thorned Jaw"],
		itemId = 197115,
		npcs = { 187559 },
		chance = 50,
		questId = { 69316 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
			{ m = CONSTANTS.UIMAPIDS.THALDRASZUS },
		},
	},
	["Highland Drake: Coiled Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Highland Drake: Coiled Horns"],
		itemId = 197125,
		npcs = { 195431, 193658 },
		chance = 50,
		questId = { 69326 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THALDRASZUS },
		},
	},
	["Highland Drake: Stag Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Highland Drake: Stag Horns"],
		itemId = 197130,
		npcs = { 193210, 193176 },
		chance = 50,
		questId = { 69331 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THALDRASZUS },
		},
	},
	["Highland Drake: Hairy Cheek"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Highland Drake: Hairy Cheek"],
		itemId = 197131,
		npcs = { 186200 },
		chance = 50,
		questId = { 69332 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
		},
	},
	-- Cliffside Wylderdrake
	["Cliffside Wylderdrake: Blunt Spiked Tail"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Cliffside Wylderdrake: Blunt Spiked Tail"],
		itemId = 197019,
		npcs = { 191611 },
		chance = 50,
		questId = { 69219 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
		},
	},
	["Cliffside Wylderdrake: Black Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Cliffside Wylderdrake: Black Horns"],
		itemId = 196991,
		npcs = { 187209, 187886, 189289 },
		chance = 50,
		questId = { 69191 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
		},
	},
	["Cliffside Wylderdrake: Heavy Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Cliffside Wylderdrake: Heavy Horns"],
		itemId = 196992,
		npcs = { 193722, 187111, 196010, 193143, 193243 },
		chance = 50,
		questId = { 69192 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THALDRASZUS },
		},
	},
	["Cliffside Wylderdrake: Horned Nose"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Cliffside Wylderdrake: Horned Nose"],
		itemId = 197005,
		npcs = { 191611 },
		chance = 50,
		questId = { 69205 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
		},
	},
	["Cliffside Wylderdrake: Head Mane"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Cliffside Wylderdrake: Head Mane"],
		itemId = 196976,
		npcs = { 184853, 192949, 192983, 194401, 193273 },
		chance = 50,
		questId = { 69176 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
			{ m = CONSTANTS.UIMAPIDS.THALDRASZUS },
		},
	},
	["Cliffside Wylderdrake: Ears"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Cliffside Wylderdrake: Ears"],
		itemId = 196982,
		npcs = { 192749 },
		chance = 20,
		questId = { 69182 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
		},
	},
	["Cliffside Wylderdrake: Maned Neck"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Cliffside Wylderdrake: Maned Neck"],
		itemId = 197023,
		npcs = { 187209, 198703, 193116 },
		chance = 50,
		questId = { 69223 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
		},
	},
	["Cliffside Wylderdrake: Branched Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Cliffside Wylderdrake: Branched Horns"],
		itemId = 196996,
		npcs = { 187559 },
		chance = 50,
		questId = { 69196 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
		},
	},
	["Cliffside Wylderdrake: Dual Horned Chin"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Cliffside Wylderdrake: Dual Horned Chin"],
		itemId = 196973,
		npcs = { 193128, 197356, 193178 },
		chance = 50,
		questId = { 69173 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
		},
	},
	["Cliffside Wylderdrake: Finned Cheek"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Cliffside Wylderdrake: Finned Cheek"],
		itemId = 197001,
		npcs = { 187945, 196056 },
		chance = 50,
		questId = { 69201 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
			{ m = CONSTANTS.UIMAPIDS.THALDRASZUS },
		},
	},
	["Cliffside Wylderdrake: Finned Neck"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Cliffside Wylderdrake: Finned Neck"],
		itemId = 197022,
		npcs = { 193118, 193181, 194392 },
		chance = 50,
		questId = { 69222 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THE_WAKING_SHORES },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
		},
	},
	["Cliffside Wylderdrake: Black Hair"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Cliffside Wylderdrake: Black Hair"],
		itemId = 196986,
		npcs = { 193128, 197356, 193178 },
		chance = 50,
		questId = { 69186 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
		},
	},
	["Cliffside Wylderdrake: Narrow Stripes Pattern"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Cliffside Wylderdrake: Narrow Stripes Pattern"],
		itemId = 197008,
		npcs = { 193210 },
		chance = 50,
		questId = { 69208 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THALDRASZUS },
		},
	},
	["Cliffside Wylderdrake: Short Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Cliffside Wylderdrake: Short Horns"],
		itemId = 196994,
		npcs = { 193146 },
		chance = 50,
		questId = { 69194 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.THALDRASZUS },
		},
	},
	["Cliffside Wylderdrake: Spiked Back"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Cliffside Wylderdrake: Spiked Back"],
		itemId = 196970,
		npcs = { 193188, 196165 },
		chance = 50,
		questId = { 69170 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
		},
	},
	["Cliffside Wylderdrake: Maned Tail"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Cliffside Wylderdrake: Maned Tail"],
		itemId = 197016,
		npcs = { 193227, 189652, 192020, 192045 },
		chance = 50,
		questId = { 69192 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
		},
	},
	["Cliffside Wylderdrake: Coiled Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Cliffside Wylderdrake: Coiled Horns"],
		itemId = 197000,
		npcs = { 203353 },
		chance = 50,
		questId = { 69200 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.FORBIDDEN_REACH },
		},
	},
-- 10.1 Manuscripts from Rares / World Bosses / Treasures
	-- Renewed Proto Drake
	["Renewed Proto-Drake: Plated Jaw"] = {
        cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
        type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
        method = CONSTANTS.DETECTION_METHODS.USE,
        name = L["Renewed Proto-Drake: Plated Jaw"],
        itemId = 202275,
        items = { 386091, 386090, 386089, 386088 }, -- Ritual Offerings
        chance = 100,
        questId = { 73059 },
        coords = { { m = CONSTANTS.UIMAPIDS.ZARALEK_CAVERN } },
    },
    ["Renewed Proto-Drake: Short Spiked Crest"] = {
        cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
        type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
        method = CONSTANTS.DETECTION_METHODS.NPC,
        name = L["Renewed Proto-Drake: Short Spiked Crest"],
        itemId = 197364,
        npcs = { 204093 },
        chance = 50,
        questId = { 69565 },
        coords = { { m = CONSTANTS.UIMAPIDS.ZARALEK_CAVERN } },
    },

	-- Highland Drake
	["Highland Drake: Spiked Head"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Highland Drake: Spiked Head"],
		itemId = 197109,
		npcs = { 203660 },
		chance = 50,
		questId = { 69310 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.ZARALEK_CAVERN },
		},
	},
	-- Cliffside Wylderdrake
	["Cliffside Wylderdrake: Spiked Club Tail"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Cliffside Wylderdrake: Spiked Club Tail"],
		itemId = 197021,
		npcs = { 203462 },
		chance = 50,
		questId = { 69221 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.ZARALEK_CAVERN },
		},
	},
	-- Winding Slitherdrake
	["Winding Slitherdrake: Long Chin Horn"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Winding Slitherdrake: Long Chin Horn"],
		itemId = 203309,
		npcs = { 203477 },
		chance = 50,
		questId = { 73797 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.ZARALEK_CAVERN },
		},
	},
	["Winding Slitherdrake: Cluster Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Winding Slitherdrake: Cluster Horns"],
		itemId = 203331,
		npcs = { 203521 },
		chance = 50,
		questId = { 73820 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.ZARALEK_CAVERN },
		},
	},
	["Winding Slitherdrake: Ears"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Winding Slitherdrake: Ears"],
		itemId = 203320,
		npcs = { 203646 },
		chance = 50,
		questId = { 73808 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.ZARALEK_CAVERN },
		},
	},
	["Winding Slitherdrake: Curled Cheek Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Winding Slitherdrake: Curled Cheek Horns"],
		itemId = 203321,
		npcs = { 203643 },
		chance = 50,
		questId = { 73809 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.ZARALEK_CAVERN },
		},
	},
    ["Winding Slitherdrake: Curled Horns"] = {
        cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
        type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
        method = CONSTANTS.DETECTION_METHODS.NPC,
        name = L["Winding Slitherdrake: Curled Horns"],
        itemId = 203334,
        npcs = { 203592 },
        chance = 50,
        questId = { 73824 },
        coords = {
            { m = CONSTANTS.UIMAPIDS.ZARALEK_CAVERN },
        },
    },
	["Winding Slitherdrake: Plated Brow"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Winding Slitherdrake: Plated Brow"],
		itemId = 203334,
		npcs = { 203592 },
		chance = 50,
		questId = { 73824 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.ZARALEK_CAVERN },
		},
	},
	["Winding Slitherdrake: Split Jaw Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Winding Slitherdrake: Split Jaw Horns"],
		itemId = 203345,
		npcs = { 203515 },
		chance = 50,
		questId = { 73836 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.ZARALEK_CAVERN },
		},
	},
	["Winding Slitherdrake: Small Finned Tail"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Winding Slitherdrake: Small Finned Tail"],
		itemId = 203358,
		npcs = { 203625 },
		chance = 50,
		questId = { 73850 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.ZARALEK_CAVERN },
		},
	},
	["Winding Slitherdrake: Heavy Scales"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Winding Slitherdrake: Heavy Scales"],
		itemId = 205341,
		npcs = { 203466 },
		chance = 50,
		questId = { 75743 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.ZARALEK_CAVERN },
		},
	},
	["Winding Slitherdrake: Impaler Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Winding Slitherdrake: Impaler Horns"],
		itemId = 203339,
		npcs = { 200111 },
		chance = 50,
		questId = { 73830 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.ZARALEK_CAVERN },
		},
	},
	["Winding Slitherdrake: Large Finned Throat"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Winding Slitherdrake: Large Finned Throat"],
		itemId = 203363,
		npcs = { 203664 },
		chance = 50,
		questId = { 73855 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.ZARALEK_CAVERN },
		},
	},
	["Winding Slitherdrake: White Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Winding Slitherdrake: White Horns"],
		itemId = 203328,
		npcs = { 203627 },
		chance = 50,
		questId = { 73816 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.ZARALEK_CAVERN },
		},
	},
	["Winding Slitherdrake: Antler Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Winding Slitherdrake: Antler Horns"],
		itemId = 203338,
		npcs = { 203662 },
		chance = 50,
		questId = { 73829 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.ZARALEK_CAVERN },
		},
	},
	["Winding Slitherdrake: Hairy Crest"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Winding Slitherdrake: Hairy Crest"],
		itemId = 203318,
		npcs = { 203480 },
		chance = 50,
		questId = { 73806 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.ZARALEK_CAVERN },
		},
	},
	["Winding Slitherdrake: Spiked Chin"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Winding Slitherdrake: Spiked Chin"],
		itemId = 203313,
		items = { 401844 },
		chance = 100,
		questId = { 73801 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.ZARALEK_CAVERN },
		},
	},
-- 10.2 Manuscripts from Rares / World Bosses / Treasures
	-- Winding Slitherdrake
	["Winding Slitherdrake: Small Spiked Crest"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Winding Slitherdrake: Small Spiked Crest"],
		itemId = 203315,
		items = { 408719 }, -- Small Somnut
		chance = 100,
		questId = { 73803 },
		coords = { { m = CONSTANTS.UIMAPIDS.THE_EMERALD_DREAM } },
	},
	["Winding Slitherdrake: Spiked Tail"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Winding Slitherdrake: Spiked Tail"],
		itemId = 203357,
		items = { 408719 }, -- Small Somnut
		chance = 100,
		questId = { 73849 },
		coords = { { m = CONSTANTS.UIMAPIDS.THE_EMERALD_DREAM } },
	},
	["Winding Slitherdrake: Spiked Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Winding Slitherdrake: Spiked Horns"],
		itemId = 203332,
		items = { 408719 }, -- Small Somnut
		chance = 100,
		questId = { 73821 },
		coords = { { m = CONSTANTS.UIMAPIDS.THE_EMERALD_DREAM } },
	},
	-- Flourishing Whimsydrake
	["Flourishing Whimsydrake: Sunrise Scales"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.ENCOUNTER,
		encounters = {
			2828, -- Aurostor
		},
		name = L["Flourishing Whimsydrake: Sunrise Scales"],
		itemId = 210480,
		npcs = { 209574 },
		chance = 50,
		questId = { 78409 },
		coords = { { m = CONSTANTS.UIMAPIDS.THE_EMERALD_DREAM } },
	},
	-- Grotto Netherwing Drake
	["Grotto Netherwing Drake: Barbed Tail"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.ZONE,
		name = L["Grotto Netherwing Drake: Barbed Tail"],
		itemId = 207779,
		zones = { "2200" },
		chance = 500,
		questId = { 77150 },
		coords = { { m = CONSTANTS.UIMAPIDS.THE_EMERALD_DREAM } },
	},
	["Grotto Netherwing Drake: Short Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.ZONE,
		name = L["Grotto Netherwing Drake: Short Horns"],
		itemId = 207771,
		zones = { "2200" },
		chance = 500,
		questId = { 77142 },
		coords = { { m = CONSTANTS.UIMAPIDS.THE_EMERALD_DREAM } },
	},
	["Grotto Netherwing Drake: Triple Spiked Crest"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.ZONE,
		name = L["Grotto Netherwing Drake: Triple Spiked Crest"],
		itemId = 207766,
		zones = { "2200" },
		chance = 500,
		questId = { 77137 },
		coords = { { m = CONSTANTS.UIMAPIDS.THE_EMERALD_DREAM } },
	},
-- 10.1 Fyrakk Assaults
	-- Renewed Proto Drake
	["Renewed Proto-Drake: Bruiser Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Renewed Proto-Drake: Bruiser Horns"],
		itemId = 202277,
		npcs = { 201673, 203411 },
		chance = 100,
		questId = { 73057 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
		},
	},
	["Renewed Proto-Drake: Black and Red Armor"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Renewed Proto-Drake: Black and Red Armor"],
		itemId = 197348,
		npcs = { 201673, 203411 },
		chance = 100,
		questId = { 69549 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
		},
	},
	["Renewed Proto-Drake: Bronze and Pink Armor"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Renewed Proto-Drake: Bronze and Pink Armor"],
		itemId = 197353,
		items = { 398815, 386559 },
		chance = 100,
		questId = { 69554 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
		},
	},
	-- Windborne Velocidrake
	["Windborne Velocidrake: Bronze and Green Armor"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Windborne Velocidrake: Bronze and Green Armor"],
		itemId = 197577,
		items = { 398815, 386559 },
		chance = 100,
		questId = { 69781 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
		},
	},
	-- Highland Drake
	["Highland Drake: Bronze and Green Armor"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Highland Drake: Bronze and Green Armor"],
		itemId = 197156,
		items = { 398815, 386559 },
		chance = 100,
		questId = { 69357 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
		},
	},
	-- Cliffside Wylderdrake
	["Cliffside Wylderdrake: Bronze and Teal Armor"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Cliffside Wylderdrake: Bronze and Teal Armor"],
		itemId = 196965,
		items = { 398815, 386559 },
		chance = 100,
		questId = { 69165 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
		},
	},
	-- Winding Slitherdrake
	["Winding Slitherdrake: Green and Bronze Armor"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Winding Slitherdrake: Green and Bronze Armor"],
		itemId = 203299,
		items = { 398815, 386559 },
		chance = 100,
		questId = { 73787 },
		coords = {
			{ m = CONSTANTS.UIMAPIDS.OHN_AHRAN_PLAINS },
			{ m = CONSTANTS.UIMAPIDS.THE_AZURE_SPAN },
		},
	},
-- 10.2 Superbloom
	-- Renewed Proto Drake
	["Renewed Proto-Drake: Green Hair"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Renewed Proto-Drake: Green Hair"],
		itemId = 197371,
		items = { 211413 },
		chance = 100,
		questId = { 69572 },
		coords = { { m = CONSTANTS.UIMAPIDS.THE_EMERALD_DREAM } },
	},
	-- Winding Slitherdrake
	["Winding Slitherdrake: Single Jaw Horn"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Winding Slitherdrake: Single Jaw Horn"],
		itemId = 203344,
		items = { 211413 },
		chance = 100,
		questId = { 73835 },
		coords = { { m = CONSTANTS.UIMAPIDS.THE_EMERALD_DREAM } },
	},
	["Winding Slitherdrake: Heavy Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Winding Slitherdrake: Heavy Horns"],
		itemId = 203329,
		items = { 211413 },
		chance = 100,
		questId = { 73817 },
		coords = { { m = CONSTANTS.UIMAPIDS.THE_EMERALD_DREAM } },
	},
	["Winding Slitherdrake: Cluster Jaw Horn"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Winding Slitherdrake: Cluster Jaw Horn"],
		itemId = 203340,
		items = { 211413 },
		chance = 100,
		questId = { 73831 },
		coords = { { m = CONSTANTS.UIMAPIDS.THE_EMERALD_DREAM } },
	},
	-- Grotto Netherwing Drake
	["Grotto Netherwing Drake: Single Horned Crest"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Grotto Netherwing Drake: Single Horned Crest"],
		itemId = 207763,
		items = { 211413 },
		chance = 100,
		questId = { 77134 },
		coords = { { m = CONSTANTS.UIMAPIDS.THE_EMERALD_DREAM } },
	},
	["Grotto Netherwing Drake: Tempestuous Pattern"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Grotto Netherwing Drake: Tempestuous Pattern"],
		itemId = 207767,
		items = { 211413 },
		chance = 100,
		questId = { 77138 },
		coords = { { m = CONSTANTS.UIMAPIDS.THE_EMERALD_DREAM } },
	},
	["Grotto Netherwing Drake: Finned Jaw"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Grotto Netherwing Drake: Finned Jaw"],
		itemId = 207774,
		items = { 211413 },
		chance = 100,
		questId = { 77145 },
		coords = { { m = CONSTANTS.UIMAPIDS.THE_EMERALD_DREAM } },
	},
	["Grotto Netherwing Drake: Chin Spike"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Grotto Netherwing Drake: Chin Spike"],
		itemId = 207762,
		items = { 211413 },
		chance = 100,
		questId = { 77133 },
		coords = { { m = CONSTANTS.UIMAPIDS.THE_EMERALD_DREAM } },
	},
-- 10.2 Dreamseeds
	-- Grotto Netherwing Drake
	["Grotto Netherwing Drake: Outcast Pattern"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Grotto Netherwing Drake: Outcast Pattern"],
		itemId = 207769,
		items = { 406119, 409225, 406956, 406143, 406143, 406139, 406148, 409848, 406121, 406135, 406355, 406124, 409228, 409221, 406119 }, --These are only the Purple colored Dreamseeds, I'm not adding 51 ids here
		chance = 100,
		questId = { 77140 },
		coords = { { m = CONSTANTS.UIMAPIDS.THE_EMERALD_DREAM } },
	},
	["Grotto Netherwing Drake: Long Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Grotto Netherwing Drake: Long Horns"],
		itemId = 207772,
		items = { 406119, 409225, 406956, 406143, 406143, 406139, 406148, 409848, 406121, 406135, 406355, 406124, 409228, 409221, 406119 }, --These are only the Purple colored Dreamseeds, I'm not adding 51 ids here
		chance = 100,
		questId = { 77143 },
		coords = { { m = CONSTANTS.UIMAPIDS.THE_EMERALD_DREAM } },
	},
	["Grotto Netherwing Drake: Cluster Spiked Back"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Grotto Netherwing Drake: Cluster Spiked Back"],
		itemId = 207759,
		items = { 406119, 409225, 406956, 406143, 406143, 406139, 406148, 409848, 406121, 406135, 406355, 406124, 409228, 409221, 406119 }, --These are only the Purple colored Dreamseeds, I'm not adding 51 ids here
		chance = 100,
		questId = { 77130 },
		coords = { { m = CONSTANTS.UIMAPIDS.THE_EMERALD_DREAM } },
	},
	["Grotto Netherwing Drake: Head Spike"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.USE,
		name = L["Grotto Netherwing Drake: Head Spike"],
		itemId = 207764,
		items = { 406119, 409225, 406956, 406143, 406143, 406139, 406148, 409848, 406121, 406135, 406355, 406124, 409228, 409221, 406119 }, --These are only the Purple colored Dreamseeds, I'm not adding 51 ids here
		chance = 100,
		questId = { 77135 },
		coords = { { m = CONSTANTS.UIMAPIDS.THE_EMERALD_DREAM } },
	},
-- Dragonflight Dungeons
	-- Renewed Proto Drake
	["Renewed Proto-Drake: Heavy Scales"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Renewed Proto-Drake: Heavy Scales"],
		itemId = 197397,
		tooltipNpcs = { 189901 },
		npcs = { 99999 },
		statisticId = { 16080, 16081, 16082 },
		questId = { 69598 },
		chance = 10,
		instanceDifficulties = {
			[CONSTANTS.INSTANCE_DIFFICULTIES.NORMAL_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_DUNGEON] = true,
		 },
        coords = { { m = CONSTANTS.UIMAPIDS.NELTHARUS, i = true } },
	},


	["Renewed Proto-Drake: Ears"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Renewed Proto-Drake: Ears"],
		itemId = 197376,
		tooltipNpcs = { 189901 },
		npcs = { 99999 },
		statisticId = { 16080, 16081, 16082 },
		questId = { 69577 },
		chance = 10,
		instanceDifficulties = {
			[CONSTANTS.INSTANCE_DIFFICULTIES.NORMAL_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_DUNGEON] = true,
		},
		coords = { { m = CONSTANTS.UIMAPIDS.NELTHARUS, i = true } },
	},
	["Renewed Proto-Drake: Skyterror Pattern"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Renewed Proto-Drake: Skyterror Pattern"],
		itemId = 197396,
		tooltipNpcs = { 186121 },
		npcs = { 99999 },
		statisticId = { 16074, 16075, 16076 },
		questId = { 69597 },
		chance = 10,
		instanceDifficulties = {
			[CONSTANTS.INSTANCE_DIFFICULTIES.NORMAL_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_DUNGEON] = true,
		},
		coords = { { m = CONSTANTS.UIMAPIDS.BRACKENHIDE_HOLLOW, i = true } },
	},
	["Renewed Proto-Drake: Beaked Snout"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Renewed Proto-Drake: Beaked Snout"],
		itemId = 197401,
		tooltipNpcs = { 199790 },
		npcs = { 99999 },
		statisticId = { 16083, 16084, 16085 },
		questId = { 69602 },
		chance = 10,
		instanceDifficulties = {
			[CONSTANTS.INSTANCE_DIFFICULTIES.NORMAL_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_DUNGEON] = true,
		},
		coords = { { m = CONSTANTS.UIMAPIDS.RUBY_LIFE_POOLS, i = true } },
	},
	-- Windborne Velocidrake
	["Windborne Velocidrake: Gray Hair"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Windborne Velocidrake: Gray Hair"],
		itemId = 197396,
		tooltipNpcs = { 186121 },
		npcs = { 99999 },
		statisticId = { 16074, 16075, 16076 },
		questId = { 69597 },
		chance = 10,
		instanceDifficulties = {
			[CONSTANTS.INSTANCE_DIFFICULTIES.NORMAL_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_DUNGEON] = true,
		},
		coords = { { m = CONSTANTS.UIMAPIDS.BRACKENHIDE_HOLLOW, i = true } },
	},
	["Windborne Velocidrake: Wavy Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Windborne Velocidrake: Wavy Horns"],
		itemId = 197601,
		tooltipNpcs = { 199790 },
		npcs = { 99999 },
		statisticId = { 16083, 16084, 16085 },
		questId = { 69805 },
		chance = 10,
		instanceDifficulties = {
			[CONSTANTS.INSTANCE_DIFFICULTIES.NORMAL_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_DUNGEON] = true,
		},
		coords = { { m = CONSTANTS.UIMAPIDS.RUBY_LIFE_POOLS, i = true } },
	},
	["Windborne Velocidrake: Reaver Pattern"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Windborne Velocidrake: Reaver Pattern"],
		itemId = 197635,
		tooltipNpcs = { 186151 },
		npcs = { 99999 },
		statisticId = { 16092, 16093, 16094 },
		questId = { 69846 },
		chance = 10,
		instanceDifficulties = {
			[CONSTANTS.INSTANCE_DIFFICULTIES.NORMAL_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_DUNGEON] = true,
		},
		coords = { { m = CONSTANTS.UIMAPIDS.THE_NOKHUD_OFFENSIVE, i = true } }, -- This needs to be added into SharedConstants, it's missing ATM
	},
	["Windborne Velocidrake: Feathery Tail"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Windborne Velocidrake: Feathery Tail"],
		itemId = 197625,
		tooltipNpcs = { 186151 },
		npcs = { 99999 },
		statisticId = { 16092, 16093, 16094 },
		questId = { 69829 },
		chance = 10,
		instanceDifficulties = {
			[CONSTANTS.INSTANCE_DIFFICULTIES.NORMAL_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_DUNGEON] = true,
		},
		coords = { { m = CONSTANTS.UIMAPIDS.THE_NOKHUD_OFFENSIVE, i = true } }, -- This needs to be added into SharedConstants, it's missing ATM
	},
	-- Highland Drake
	["Highland Drake: Heavy Scales"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Highland Drake: Heavy Scales"],
		itemId = 197147,
		tooltipNpcs = { 190609 },
		npcs = { 99999 },
		statisticId = { 16086, 16087, 16088 },
		questId = { 69348 },
		chance = 10,
		instanceDifficulties = {
			[CONSTANTS.INSTANCE_DIFFICULTIES.NORMAL_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_DUNGEON] = true,
		},
		coords = { { m = CONSTANTS.UIMAPIDS.ALGETHAR_ACADEMY, i = true } },
	},
	["Highland Drake: Single Horned Head"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Highland Drake: Single Horned Head"],
		itemId = 197112,
		tooltipNpcs = { 190609 },
		npcs = { 99999 },
		statisticId = { 16086, 16087, 16088 },
		questId = { 69313 },
		chance = 10,
		instanceDifficulties = {
			[CONSTANTS.INSTANCE_DIFFICULTIES.NORMAL_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_DUNGEON] = true,
		},
		coords = { { m = CONSTANTS.UIMAPIDS.ALGETHAR_ACADEMY, i = true } },
	},
	["Highland Drake: Small Spotted Pattern"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Highland Drake: Single Horned Head"],
		itemId = 197140,
		tooltipNpcs = { 186738 },
		npcs = { 99999 },
		statisticId = { 16089, 16090, 16091 },
		questId = { 69341 },
		chance = 10,
		instanceDifficulties = {
			[CONSTANTS.INSTANCE_DIFFICULTIES.NORMAL_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_DUNGEON] = true,
		},
		coords = { { m = CONSTANTS.UIMAPIDS.AZURE_VAULT, i = true } },
	},
	["Highland Drake: Grand Thorn Horns"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Highland Drake: Grand Thorn Horns"],
		itemId = 197127,
		tooltipNpcs = { 186738 },
		npcs = { 99999 },
		statisticId = { 16089, 16090, 16091 },
		questId = { 69328 },
		chance = 10,
		instanceDifficulties = {
			[CONSTANTS.INSTANCE_DIFFICULTIES.NORMAL_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_DUNGEON] = true,
		},
		coords = { { m = CONSTANTS.UIMAPIDS.AZURE_VAULT, i = true } },
	},
	-- Cliffside Wylderdrake
	["Cliffside Wylderdrake: Wide Stripes Pattern"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Cliffside Wylderdrake: Wide Stripes Pattern"],
		itemId = 197007,
		tooltipNpcs = { 189729 },
		npcs = { 99999 },
		statisticId = { 16077, 16078, 16079 },
		questId = { 69207 },
		chance = 10,
		instanceDifficulties = {
			[CONSTANTS.INSTANCE_DIFFICULTIES.NORMAL_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_DUNGEON] = true,
		},
		coords = { { m = CONSTANTS.UIMAPIDS.HALLS_OF_INFUSION, i = true } },
	},
	["Cliffside Wylderdrake: Head Fin"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.NPC,
		name = L["Cliffside Wylderdrake: Head Fin"],
		itemId = 196975,
		tooltipNpcs = { 189729 },
		npcs = { 99999 },
		statisticId = { 16077, 16078, 16079 },
		questId = { 69175 },
		chance = 10,
		instanceDifficulties = {
			[CONSTANTS.INSTANCE_DIFFICULTIES.NORMAL_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_DUNGEON] = true,
		},
		coords = { { m = CONSTANTS.UIMAPIDS.HALLS_OF_INFUSION, i = true } },
	},
-- Dawn of the Infinite Dungeon
	-- Visage of the Infinite Skins
	["Renewed Proto-Drake: Visage of the Infinite"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.ENCOUNTER,
		encounter = {
			2673, -- Chrono-Lord Deios, Dawn of the Infinite
		},
		name = L["Renewed Proto-Drake: Visage of the Infinite"],
		itemId = 208104,
		npcs = { 199000 },
		questId = { 77255 },
		chance = 20,
		instanceDifficulties = {
			[CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_DUNGEON] = true,
		},
		lockoutDetails = {
			mode = CONSTANTS.DEFEAT_DETECTION.MODE_AND,
			{
				encounterName = "Chrono-Lord Deios",
				instanceDifficulties = { [CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_DUNGEON] = true, [CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_DUNGEON] = true, },
			},
		},
		coords = { { m = CONSTANTS.UIMAPIDS.CROSSROADS_OF_FATE, i = true } },
	},
	["Windborne Velocidrake: Visage of the Infinite"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.ENCOUNTER,
		encounter = {
			2673, -- Chrono-Lord Deios, Dawn of the Infinite
		},
		name = L["Windborne Velocidrake: Visage of the Infinite"],
		itemId = 208105,
		npcs = { 199000 },
		questId = { 77256 },
		chance = 20,
		instanceDifficulties = {
			[CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_DUNGEON] = true,
		},
		lockoutDetails = {
			mode = CONSTANTS.DEFEAT_DETECTION.MODE_AND,
			{
				encounterName = "Chrono-Lord Deios",
				instanceDifficulties = { [CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_DUNGEON] = true, [CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_DUNGEON] = true, },
			},
		},
		coords = { { m = CONSTANTS.UIMAPIDS.CROSSROADS_OF_FATE, i = true } },
	},
	["Highland Drake: Visage of the Infinite"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.ENCOUNTER,
		encounter = {
			2673, -- Chrono-Lord Deios, Dawn of the Infinite
		},
		name = L["Highland Drake: Visage of the Infinite"],
		itemId = 208103,
		npcs = { 199000 },
		questId = { 77257 },
		chance = 20,
		instanceDifficulties = {
			[CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_DUNGEON] = true,
		},
		lockoutDetails = {
			mode = CONSTANTS.DEFEAT_DETECTION.MODE_AND,
			{
				encounterName = "Chrono-Lord Deios",
				instanceDifficulties = { [CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_DUNGEON] = true, [CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_DUNGEON] = true, },
			},
		},
		coords = { { m = CONSTANTS.UIMAPIDS.CROSSROADS_OF_FATE, i = true } },
	},
	["Cliffside Wylderdrake: Visage of the Infinite"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.ENCOUNTER,
		encounter = {
			2673, -- Chrono-Lord Deios, Dawn of the Infinite
		},
		name = L["Cliffside Wylderdrake: Visage of the Infinite"],
		itemId = 208102,
		npcs = { 199000 },
		questId = { 77258 },
		chance = 20,
		instanceDifficulties = {
			[CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_DUNGEON] = true,
		},
		lockoutDetails = {
			mode = CONSTANTS.DEFEAT_DETECTION.MODE_AND,
			{
				encounterName = "Chrono-Lord Deios",
				instanceDifficulties = { [CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_DUNGEON] = true, [CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_DUNGEON] = true, },
			},
		},
		coords = { { m = CONSTANTS.UIMAPIDS.CROSSROADS_OF_FATE, i = true } },
	},
	["Winding Slitherdrake: Visage of the Infinite"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.ENCOUNTER,
		encounter = {
			2673, -- Chrono-Lord Deios, Dawn of the Infinite
		},
		name = L["Renewed Proto-Drake: Visage of the Infinite"],
		itemId = 208106,
		npcs = { 199000 },
		questId = { 77259 },
		chance = 20,
		instanceDifficulties = {
			[CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_DUNGEON] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_DUNGEON] = true,
		},
		lockoutDetails = {
			mode = CONSTANTS.DEFEAT_DETECTION.MODE_AND,
			{
				encounterName = "Chrono-Lord Deios",
				instanceDifficulties = { [CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_DUNGEON] = true, [CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_DUNGEON] = true, },
			},
		},
		coords = { { m = CONSTANTS.UIMAPIDS.CROSSROADS_OF_FATE, i = true } },
	},
-- Raid Drops
	-- Vault of the Incarnates
	["Renewed Proto-Drake: Embodiment of the Storm-Eater"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.BOSS,
		name = L["Renewed Proto-Drake: Embodiment of the Storm-Eater"],
		itemId = 201790,
		npcs = { 99999 },
		tooltipNpcs = { 189492 },
		questId = { 72367 },
		chance = 100,
		statisticId = { 16370, 16378, 16386, 16394 },
		lockBossName = "Raszageth",
		instanceDifficulties = {
			[CONSTANTS.INSTANCE_DIFFICULTIES.NORMAL_RAID] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_RAID] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_RAID] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.LFR] = true,
		},
		coords = { { m = CONSTANTS.UIMAPIDS.VAULT_OF_THE_INCARNATES, i = true } },
	},
	-- Aberrus, the Shadowed Crucible
	["Highland Drake: Embodiment of the Hellforged"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.BOSS,
		name = L["Highland Drake: Embodiment of the Hellforged"],
		itemId = 205876,
		npcs = { 99999 },
		tooltipNpcs = { 201754 },
		questId = { 75967 },
		chance = 100,
		statisticId = { 18187, 18198, 18218, 18227 },
		lockBossName = "Sarkareth",
		instanceDifficulties = {
			[CONSTANTS.INSTANCE_DIFFICULTIES.NORMAL_RAID] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_RAID] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_RAID] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.LFR] = true,
		},
		coords = { { m = CONSTANTS.UIMAPIDS.ABERRUS_RAID, i = true } },
	},
	-- Amirdrassil, the Dream's Hope
	["Renewed Proto-Drake: Embodiment of the Blazing"] = {
		cat = CONSTANTS.ITEM_CATEGORIES.DRAGONFLIGHT,
		type = CONSTANTS.ITEM_TYPES.MANUSCRIPT,
		method = CONSTANTS.DETECTION_METHODS.BOSS,
		name = L["Renewed Proto-Drake: Embodiment of the Blazing"],
		itemId = 210536,
		npcs = { 99999 },
		tooltipNpcs = { 204931 },
		questId = { 78451 },
		chance = 100,
		statisticId = { 19359, 19368, 19377, 19386 },
		lockBossName = "Fyrakk",
		instanceDifficulties = {
			[CONSTANTS.INSTANCE_DIFFICULTIES.NORMAL_RAID] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.HEROIC_RAID] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.MYTHIC_RAID] = true,
			[CONSTANTS.INSTANCE_DIFFICULTIES.LFR] = true,
		},
		coords = { { m = CONSTANTS.UIMAPIDS.AMIRDRASSIL_RAID, i = true } },
	},
}
-- If you see this line, consider yourself bitten :3  -Rogu <3
Rarity.ItemDB.MergeItems(Rarity.ItemDB.manuscripts, dragonflightManuscripts)
return dragonflightManuscripts
